# Generated by Django 4.2.5 on 2023-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_status_students_amount_students_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
